### ISSUE TITLE
Parsing error: identifier directly after number

### ISSUE THREAD

**Issue by terrylb** [weareadjacent/lambda-lightsail-backup#1]
Hi Tom,

I added two instances into the BACKUP_INSTANCES array:

`const BACKUP_INSTANCES = process.env.BACKUP_INSTANCES.split(',') || [dopbb-LAMP_Stack-512MB-Oregon-1,Vforum-LAMP_Stack-512MB-Oregon-1];`

This produces a red error box on this line and hovering over it says, `"Parsing error: identifier directly after number"`

If I put the instance names in quotes,
`const BACKUP_INSTANCES = process.env.BACKUP_INSTANCES.split(',') || ["dopbb-LAMP_Stack-512MB-Oregon-1","Vforum-LAMP_Stack-512MB-Oregon-1"];`
then I get this execution error:
```
{
  "errorMessage": "Cannot read property 'split' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)"
  ]
}

```
```
START RequestId: 5b09d197-dbdf-11e8-ab90-71793f21f446 Version: $LATEST
module initialization error: TypeError
    at Object.<anonymous> (/var/task/index.js:15:55)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
END RequestId: 5b09d197-dbdf-11e8-ab90-71793f21f446
REPORT RequestId: 5b09d197-dbdf-11e8-ab90-71793f21f446	Duration: 82.62 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 56 MB	
module initialization error
TypeError
```

**Comment by terrylb** [comment]
Oops! I was trying to add the instance names inline into the code but I see now that you mean the Environment variables section in the Lambda GUI. All is working as expected.

**Comment by tommcc** [comment]
Beat me to it. Glad you got it working @terrylb !
